import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Recipe from '../models/Recipe.js';

dotenv.config();

const recipes = [
  // Breakfast Recipes
  {
    title: 'Overnight Oats with Berries',
    description: 'A nutritious and easy breakfast packed with fiber and antioxidants',
    ingredients: [
      { name: 'Rolled oats', amount: '1/2', unit: 'cup' },
      { name: 'Almond milk', amount: '1/2', unit: 'cup' },
      { name: 'Greek yogurt', amount: '1/4', unit: 'cup' },
      { name: 'Mixed berries', amount: '1/2', unit: 'cup' },
      { name: 'Chia seeds', amount: '1', unit: 'tbsp' },
      { name: 'Honey', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Mix oats, almond milk, and chia seeds in a jar',
      'Stir in Greek yogurt and honey',
      'Top with mixed berries',
      'Refrigerate overnight and enjoy in the morning',
    ],
    tags: ['vegetarian', 'glutenFree', 'highFiber', 'quickPrep', 'easy', 'complexCarbs'],
    nutrition: {
      calories: 320,
      protein: 12,
      carbs: 52,
      fat: 8,
      fiber: 10,
      sugar: 18,
      sodium: 45,
    },
    mealType: 'breakfast',
    prepTime: 5,
    servings: 1,
  },
  {
    title: 'Avocado Toast with Eggs',
    description: 'Protein-rich breakfast with healthy fats',
    ingredients: [
      { name: 'Whole grain bread', amount: '2', unit: 'slices' },
      { name: 'Avocado', amount: '1/2', unit: 'medium' },
      { name: 'Eggs', amount: '2', unit: 'large' },
      { name: 'Cherry tomatoes', amount: '1/4', unit: 'cup' },
      { name: 'Salt', amount: '1/4', unit: 'tsp' },
      { name: 'Black pepper', amount: '1/4', unit: 'tsp' },
    ],
    instructions: [
      'Toast the bread slices',
      'Mash avocado and spread on toast',
      'Fry or poach eggs',
      'Place eggs on avocado toast',
      'Top with cherry tomatoes, salt, and pepper',
    ],
    tags: ['vegetarian', 'highProtein', 'complexCarbs', 'ironRich', 'quickPrep'],
    nutrition: {
      calories: 380,
      protein: 18,
      carbs: 28,
      fat: 22,
      fiber: 12,
      sugar: 4,
      sodium: 420,
    },
    mealType: 'breakfast',
    prepTime: 10,
    servings: 1,
  },
  {
    title: 'Green Smoothie Bowl',
    description: 'Energizing smoothie bowl with spinach and fruits',
    ingredients: [
      { name: 'Spinach', amount: '2', unit: 'cups' },
      { name: 'Banana', amount: '1', unit: 'medium' },
      { name: 'Mango', amount: '1/2', unit: 'cup' },
      { name: 'Coconut milk', amount: '1/2', unit: 'cup' },
      { name: 'Protein powder', amount: '1', unit: 'scoop' },
      { name: 'Granola', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Blend spinach, banana, mango, and coconut milk',
      'Add protein powder and blend until smooth',
      'Pour into a bowl',
      'Top with granola',
    ],
    tags: ['vegetarian', 'vegan', 'glutenFree', 'highProtein', 'ironRich', 'quickPrep', 'easy', 'dopamineBoosting'],
    nutrition: {
      calories: 350,
      protein: 20,
      carbs: 45,
      fat: 10,
      fiber: 8,
      sugar: 32,
      sodium: 120,
    },
    mealType: 'breakfast',
    prepTime: 5,
    servings: 1,
  },
  {
    title: 'Greek Yogurt Parfait',
    description: 'High-protein breakfast with probiotics',
    ingredients: [
      { name: 'Greek yogurt', amount: '1', unit: 'cup' },
      { name: 'Granola', amount: '1/4', unit: 'cup' },
      { name: 'Blueberries', amount: '1/2', unit: 'cup' },
      { name: 'Strawberries', amount: '1/2', unit: 'cup' },
      { name: 'Almonds', amount: '1', unit: 'tbsp' },
      { name: 'Honey', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Layer Greek yogurt in a glass',
      'Add granola and berries',
      'Repeat layers',
      'Top with almonds and drizzle with honey',
    ],
    tags: ['vegetarian', 'glutenFree', 'highProtein', 'quickPrep', 'easy', 'magnesiumRich'],
    nutrition: {
      calories: 340,
      protein: 24,
      carbs: 42,
      fat: 10,
      fiber: 6,
      sugar: 28,
      sodium: 80,
    },
    mealType: 'breakfast',
    prepTime: 5,
    servings: 1,
  },
  // Lunch Recipes
  {
    title: 'Quinoa Salad with Chickpeas',
    description: 'Protein-packed vegetarian lunch with Mediterranean flavors',
    ingredients: [
      { name: 'Quinoa', amount: '1/2', unit: 'cup' },
      { name: 'Chickpeas', amount: '1/2', unit: 'cup' },
      { name: 'Cucumber', amount: '1/2', unit: 'medium' },
      { name: 'Cherry tomatoes', amount: '1/2', unit: 'cup' },
      { name: 'Feta cheese', amount: '2', unit: 'tbsp' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Drain and rinse chickpeas',
      'Dice cucumber and halve tomatoes',
      'Mix quinoa, chickpeas, vegetables, and feta',
      'Dress with olive oil and lemon juice',
    ],
    tags: ['vegetarian', 'glutenFree', 'highProtein', 'highFiber', 'complexCarbs', 'magnesiumRich'],
    nutrition: {
      calories: 420,
      protein: 18,
      carbs: 58,
      fat: 14,
      fiber: 12,
      sugar: 8,
      sodium: 380,
    },
    mealType: 'lunch',
    prepTime: 20,
    servings: 1,
  },
  {
    title: 'Grilled Chicken Salad',
    description: 'Lean protein with fresh vegetables',
    ingredients: [
      { name: 'Chicken breast', amount: '4', unit: 'oz' },
      { name: 'Mixed greens', amount: '2', unit: 'cups' },
      { name: 'Bell peppers', amount: '1/2', unit: 'cup' },
      { name: 'Carrots', amount: '1/4', unit: 'cup' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Balsamic vinegar', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Season and grill chicken breast',
      'Slice chicken into strips',
      'Toss mixed greens with vegetables',
      'Top with grilled chicken',
      'Dress with olive oil and balsamic vinegar',
    ],
    tags: ['glutenFree', 'highProtein', 'lowCarb', 'lowSodium', 'quickPrep'],
    nutrition: {
      calories: 380,
      protein: 35,
      carbs: 15,
      fat: 18,
      fiber: 6,
      sugar: 10,
      sodium: 180,
    },
    mealType: 'lunch',
    prepTime: 15,
    servings: 1,
  },
  {
    title: 'Lentil Soup',
    description: 'Hearty and nutritious soup rich in fiber and protein',
    ingredients: [
      { name: 'Red lentils', amount: '1/2', unit: 'cup' },
      { name: 'Onion', amount: '1/4', unit: 'medium' },
      { name: 'Carrots', amount: '1/2', unit: 'cup' },
      { name: 'Celery', amount: '1/4', unit: 'cup' },
      { name: 'Vegetable broth', amount: '2', unit: 'cups' },
      { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
      { name: 'Cumin', amount: '1/2', unit: 'tsp' },
    ],
    instructions: [
      'Sauté onion, carrots, and celery',
      'Add lentils and spices',
      'Pour in vegetable broth',
      'Simmer for 25 minutes until lentils are tender',
      'Season to taste',
    ],
    tags: ['vegetarian', 'vegan', 'glutenFree', 'highProtein', 'highFiber', 'lowSodium', 'ironRich', 'magnesiumRich'],
    nutrition: {
      calories: 280,
      protein: 18,
      carbs: 48,
      fat: 2,
      fiber: 16,
      sugar: 6,
      sodium: 320,
    },
    mealType: 'lunch',
    prepTime: 30,
    servings: 1,
  },
  {
    title: 'Salmon with Sweet Potato',
    description: 'Omega-3 rich meal with complex carbohydrates',
    ingredients: [
      { name: 'Salmon fillet', amount: '4', unit: 'oz' },
      { name: 'Sweet potato', amount: '1', unit: 'medium' },
      { name: 'Broccoli', amount: '1', unit: 'cup' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Lemon', amount: '1/2', unit: 'medium' },
    ],
    instructions: [
      'Bake sweet potato at 400°F for 45 minutes',
      'Season salmon with salt and pepper',
      'Pan-sear salmon for 4-5 minutes per side',
      'Steam broccoli',
      'Serve with lemon wedge',
    ],
    tags: ['glutenFree', 'highProtein', 'complexCarbs', 'lowSodium', 'dopamineBoosting'],
    nutrition: {
      calories: 450,
      protein: 32,
      carbs: 42,
      fat: 18,
      fiber: 8,
      sugar: 12,
      sodium: 220,
    },
    mealType: 'lunch',
    prepTime: 50,
    servings: 1,
  },
  // Dinner Recipes
  {
    title: 'Turkey and Vegetable Stir-Fry',
    description: 'Lean protein with colorful vegetables',
    ingredients: [
      { name: 'Ground turkey', amount: '4', unit: 'oz' },
      { name: 'Broccoli', amount: '1', unit: 'cup' },
      { name: 'Bell peppers', amount: '1/2', unit: 'cup' },
      { name: 'Snow peas', amount: '1/2', unit: 'cup' },
      { name: 'Brown rice', amount: '1/2', unit: 'cup' },
      { name: 'Soy sauce', amount: '1', unit: 'tbsp' },
      { name: 'Ginger', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Cook brown rice according to package',
      'Brown ground turkey in a pan',
      'Add vegetables and stir-fry',
      'Season with soy sauce and ginger',
      'Serve over brown rice',
    ],
    tags: ['glutenFree', 'highProtein', 'complexCarbs', 'lowSodium', 'quickPrep'],
    nutrition: {
      calories: 420,
      protein: 32,
      carbs: 48,
      fat: 10,
      fiber: 6,
      sugar: 8,
      sodium: 480,
    },
    mealType: 'dinner',
    prepTime: 25,
    servings: 1,
  },
  {
    title: 'Vegetarian Buddha Bowl',
    description: 'Nutrient-dense bowl with grains, vegetables, and plant protein',
    ingredients: [
      { name: 'Brown rice', amount: '1/2', unit: 'cup' },
      { name: 'Chickpeas', amount: '1/2', unit: 'cup' },
      { name: 'Kale', amount: '1', unit: 'cup' },
      { name: 'Avocado', amount: '1/4', unit: 'medium' },
      { name: 'Tahini', amount: '1', unit: 'tbsp' },
      { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Cook brown rice',
      'Roast chickpeas with spices',
      'Massage kale with lemon juice',
      'Arrange rice, chickpeas, and kale in a bowl',
      'Top with avocado and tahini dressing',
    ],
    tags: ['vegetarian', 'vegan', 'glutenFree', 'highProtein', 'highFiber', 'complexCarbs', 'ironRich', 'magnesiumRich'],
    nutrition: {
      calories: 480,
      protein: 16,
      carbs: 62,
      fat: 20,
      fiber: 14,
      sugar: 6,
      sodium: 180,
    },
    mealType: 'dinner',
    prepTime: 30,
    servings: 1,
  },
  {
    title: 'Baked Cod with Vegetables',
    description: 'Light and healthy dinner with lean fish',
    ingredients: [
      { name: 'Cod fillet', amount: '5', unit: 'oz' },
      { name: 'Asparagus', amount: '1', unit: 'cup' },
      { name: 'Zucchini', amount: '1/2', unit: 'medium' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
      { name: 'Lemon', amount: '1/2', unit: 'medium' },
    ],
    instructions: [
      'Preheat oven to 400°F',
      'Place cod and vegetables on a baking sheet',
      'Drizzle with olive oil and season',
      'Bake for 15-20 minutes',
      'Serve with lemon',
    ],
    tags: ['glutenFree', 'highProtein', 'lowCarb', 'lowSodium', 'quickPrep', 'easy'],
    nutrition: {
      calories: 280,
      protein: 35,
      carbs: 12,
      fat: 10,
      fiber: 4,
      sugar: 6,
      sodium: 180,
    },
    mealType: 'dinner',
    prepTime: 20,
    servings: 1,
  },
  {
    title: 'Chicken and Vegetable Skewers',
    description: 'Grilled protein with Mediterranean vegetables',
    ingredients: [
      { name: 'Chicken breast', amount: '4', unit: 'oz' },
      { name: 'Bell peppers', amount: '1/2', unit: 'cup' },
      { name: 'Zucchini', amount: '1/2', unit: 'medium' },
      { name: 'Red onion', amount: '1/4', unit: 'medium' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Herbs', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Cut chicken and vegetables into chunks',
      'Thread onto skewers',
      'Brush with olive oil and herbs',
      'Grill for 10-12 minutes, turning occasionally',
      'Serve hot',
    ],
    tags: ['glutenFree', 'highProtein', 'lowCarb', 'lowSodium', 'quickPrep'],
    nutrition: {
      calories: 320,
      protein: 32,
      carbs: 14,
      fat: 14,
      fiber: 4,
      sugar: 8,
      sodium: 200,
    },
    mealType: 'dinner',
    prepTime: 20,
    servings: 1,
  },
  // Snack Recipes
  {
    title: 'Apple with Almond Butter',
    description: 'Satisfying snack with protein and fiber',
    ingredients: [
      { name: 'Apple', amount: '1', unit: 'medium' },
      { name: 'Almond butter', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Slice apple',
      'Serve with almond butter for dipping',
    ],
    tags: ['vegetarian', 'vegan', 'glutenFree', 'highFiber', 'quickPrep', 'easy', 'dopamineBoosting'],
    nutrition: {
      calories: 220,
      protein: 6,
      carbs: 28,
      fat: 12,
      fiber: 8,
      sugar: 20,
      sodium: 5,
    },
    mealType: 'snack',
    prepTime: 2,
    servings: 1,
  },
  {
    title: 'Greek Yogurt with Nuts',
    description: 'Protein-rich snack to keep you full',
    ingredients: [
      { name: 'Greek yogurt', amount: '1/2', unit: 'cup' },
      { name: 'Almonds', amount: '1', unit: 'tbsp' },
      { name: 'Walnuts', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Scoop Greek yogurt into a bowl',
      'Top with almonds and walnuts',
    ],
    tags: ['vegetarian', 'glutenFree', 'highProtein', 'quickPrep', 'easy', 'magnesiumRich'],
    nutrition: {
      calories: 180,
      protein: 14,
      carbs: 8,
      fat: 12,
      fiber: 2,
      sugar: 6,
      sodium: 40,
    },
    mealType: 'snack',
    prepTime: 2,
    servings: 1,
  },
  {
    title: 'Hummus with Vegetables',
    description: 'Fiber-rich snack with plant protein',
    ingredients: [
      { name: 'Hummus', amount: '1/4', unit: 'cup' },
      { name: 'Carrot sticks', amount: '1/2', unit: 'cup' },
      { name: 'Cucumber slices', amount: '1/2', unit: 'cup' },
      { name: 'Bell pepper strips', amount: '1/4', unit: 'cup' },
    ],
    instructions: [
      'Arrange vegetables on a plate',
      'Serve with hummus for dipping',
    ],
    tags: ['vegetarian', 'vegan', 'glutenFree', 'highFiber', 'quickPrep', 'easy'],
    nutrition: {
      calories: 150,
      protein: 6,
      carbs: 18,
      fat: 6,
      fiber: 8,
      sugar: 6,
      sodium: 240,
    },
    mealType: 'snack',
    prepTime: 5,
    servings: 1,
  },
  {
    title: 'Trail Mix',
    description: 'Energy-boosting mix of nuts and dried fruits',
    ingredients: [
      { name: 'Almonds', amount: '1', unit: 'tbsp' },
      { name: 'Cashews', amount: '1', unit: 'tbsp' },
      { name: 'Dried cranberries', amount: '1', unit: 'tbsp' },
      { name: 'Dark chocolate chips', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Mix all ingredients together',
      'Store in an airtight container',
    ],
    tags: ['vegetarian', 'vegan', 'glutenFree', 'quickPrep', 'easy', 'dopamineBoosting', 'magnesiumRich'],
    nutrition: {
      calories: 200,
      protein: 5,
      carbs: 16,
      fat: 14,
      fiber: 3,
      sugar: 10,
      sodium: 2,
    },
    mealType: 'snack',
    prepTime: 2,
    servings: 1,
  },
];

const seedRecipes = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/nutrimind');
    console.log('Connected to MongoDB');

    // Clear existing recipes
    await Recipe.deleteMany({});
    console.log('Cleared existing recipes');

    // Insert new recipes
    await Recipe.insertMany(recipes);
    console.log(`Seeded ${recipes.length} recipes`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding recipes:', error);
    process.exit(1);
  }
};

seedRecipes();

